version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5010
    volumes:
      - ./project:/usr/src/app
    ports:
      - 5010:5010
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=${DATABASE_URL}       
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
