version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5010
    volumes:
      - ./project:/usr/src/app
    ports:
      - 5010:5010
    env_file:
     - ./config.env
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
     - ./config.env
